version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.16.2-browsers
    working_directory: ~/react-uswds
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1.0.0-dependencies-{{ checksum "package.json" }}
            - v1.0.0-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1.0.0-dependencies-{{ checksum "package.json" }}

      - run: yarn test -w 1
      - run: yarn build-storybook && yarn loki test --requireReference --reactUri file:./storybook-static
      - run: yarn lint
      - store_artifacts:
          path: .loki/current
          destination: current
      - store_artifacts:
          path: .loki/difference
          destination: difference
      - store_artifacts:
          path: .loki/reference
          destination: reference
      - run: yarn danger ci --failOnErrors

